# Generated by Django 3.1.7 on 2021-05-29 10:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=100)),
                ('testdescription', models.CharField(default='Test', max_length=10000)),
                ('jointname', models.CharField(max_length=100)),
                ('minangle', models.IntegerField(null=True)),
                ('maxangle', models.IntegerField(null=True)),
                ('reps', models.IntegerField()),
                ('timeperrep', models.IntegerField(null=True)),
                ('img', models.ImageField(blank=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('usertype', models.IntegerField()),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_doc_id', to=settings.AUTH_USER_MODEL)),
                ('physio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_physio_id', to=settings.AUTH_USER_MODEL)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='related_uid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(null=True, verbose_name=datetime.datetime(2021, 5, 29, 10, 27, 20, 492716))),
                ('feedbackstate', models.IntegerField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.testdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.testdetails')),
            ],
        ),
    ]
