# Generated by Django 3.1.7 on 2021-04-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210413_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
