# Generated by Django 3.1.7 on 2021-04-13 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='physioID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='doctorId',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='testID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.testdetails'),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='testID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.testdetails'),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='timeStamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 13, 19, 27, 52, 711881)),
        ),
        migrations.AlterField(
            model_name='user',
            name='physioId',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
    ]
