# Generated by Django 3.1.7 on 2021-04-14 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210413_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='docId',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.user'),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='timeStamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 14, 16, 38, 41, 200759)),
        ),
        migrations.AlterField(
            model_name='user',
            name='physioId',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.user'),
        ),
    ]
