# Generated by Django 3.1.7 on 2021-05-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210529_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testhistory',
            name='feedback_state',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
