# Generated by Django 3.1.7 on 2021-05-24 06:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210414_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetails',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='timeStamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 24, 12, 7, 7, 536077)),
        ),
    ]
