# Generated by Django 3.1.7 on 2021-05-24 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210524_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetails',
            name='testDescription',
            field=models.CharField(default='Test', max_length=10000),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='timeStamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 24, 12, 17, 35, 459253)),
        ),
    ]
