# Generated by Django 3.1.7 on 2021-05-24 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210524_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='patientID',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='testID',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='testhistory',
            old_name='patientID',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='testhistory',
            old_name='testID',
            new_name='test',
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='timeStamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 24, 12, 56, 54, 635082)),
        ),
    ]
