# Generated by Django 3.1.7 on 2021-05-26 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210526_2223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetails',
        ),
        migrations.AddField(
            model_name='testhistory',
            name='feedbackState',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='timeStamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 26, 22, 41, 46, 426062)),
        ),
    ]
