# Generated by Django 3.1.7 on 2021-05-26 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210526_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='username',
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='timeStamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 26, 22, 52, 19, 6460)),
        ),
    ]
