# Generated by Django 3.1.7 on 2021-05-26 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210526_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testhistory',
            name='timeStamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 26, 22, 54, 18, 698675)),
        ),
    ]
