# Generated by Django 3.1.7 on 2021-05-26 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210526_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdetails',
            old_name='testName',
            new_name='testname',
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='timeStamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 26, 23, 3, 58, 612328)),
        ),
    ]
