# Generated by Django 3.1.7 on 2021-05-28 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210526_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdetails',
            old_name='jointName',
            new_name='jointname',
        ),
        migrations.RenameField(
            model_name='testdetails',
            old_name='maxAngle',
            new_name='maxangle',
        ),
        migrations.RenameField(
            model_name='testdetails',
            old_name='minAngle',
            new_name='minangle',
        ),
        migrations.RenameField(
            model_name='testdetails',
            old_name='testDescription',
            new_name='testdescription',
        ),
        migrations.RenameField(
            model_name='testdetails',
            old_name='timePerRep',
            new_name='timeperrep',
        ),
        migrations.RenameField(
            model_name='testhistory',
            old_name='feedbackState',
            new_name='feedbackstate',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='docId',
            new_name='docid',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='physioId',
            new_name='physioid',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='userType',
            new_name='usertype',
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='testhistory',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2021, 5, 28, 16, 30, 12, 925630)),
        ),
    ]
